DROP DATABASE IF EXISTS tariffdb;
DROP USER IF EXISTS `tariffadmin`@`%`;
DROP USER IF EXISTS `tariffuser`@`%`;
CREATE DATABASE IF NOT EXISTS tariffdb CHARACTER SET utf8mb4 COLLATE utf8mb4_swedish_ci;
CREATE USER IF NOT EXISTS `tariffadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW,
SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `tariffdb`.* TO `tariffadmin`@`%`;
CREATE USER IF NOT EXISTS `tariffuser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `tariffdb`.* TO `tariffuser`@`%`;
FLUSH PRIVILEGES;